/**
 * BrandFooter — reusable brand identity component
 *
 * Variants:
 *   'result'         → main analysis result page
 *   'compatibility'  → compatibility result page
 *   'pdf'            → future: Generated by Destiny Code Lab watermark
 *
 * Extend here when logo, company links, or PDF watermark are added.
 */

const LABELS: Record<BrandFooterVariant, string> = {
  result:        'Powered by',
  compatibility: 'Relationship Analysis by',
  pdf:           'Generated by',
};

export type BrandFooterVariant = 'result' | 'compatibility' | 'pdf';

interface BrandFooterProps {
  variant?: BrandFooterVariant;
  showSlogan?: boolean;
  className?: string;
}

export function BrandFooter({
  variant = 'result',
  showSlogan = true,
  className = '',
}: BrandFooterProps) {
  return (
    <div className={`text-center ${className}`}>

      {/* ornamental rule */}
      <div className="flex items-center justify-center gap-3 mb-2.5">
        <div className="h-px w-10 bg-gradient-to-r from-transparent to-slate-800" />
        <span className="text-slate-800 text-[9px]">◈</span>
        <div className="h-px w-10 bg-gradient-to-l from-transparent to-slate-800" />
      </div>

      {/* brand line */}
      <p className="text-[10px] tracking-[0.18em] text-slate-700">
        {LABELS[variant]}{' '}
        <span className="text-amber-500/45 font-medium tracking-[0.22em]">
          DESTINY CODE LAB
        </span>
      </p>

      {/* slogan */}
      {showSlogan && (
        <p className="text-[9px] text-slate-800 tracking-[0.12em] italic mt-1">
          Where patterns become meaning.
        </p>
      )}
    </div>
  );
}
